### ISSUE TITLE
Important: ballot encoding should say if it's a test ballot

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/ballot-encoder#4]
Both QR code and on card.

**Comment by eventualbuddha** [comment]
@benadida just v1 encoding or do we want to add this to v0 too?

**Comment by eventualbuddha** [comment]
Related: we need to pick a point at which v1 is considered frozen so that we can have compatibility. I assume that'll be when M7 is considered code-complete.

**Comment by benadida** [comment]
v1 only. For v0, let's assume it's all real ballots.
