### ISSUE TITLE
make room in the ballot encoding for ballot type

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/ballot-encoder#8]
Ballot type is something like: standard, absentee, provisional. Let's give it at least 4 bits, possibly 8. This is independent of the test bit, which should be togglable for each of these types.

**Comment by benadida** [comment]
Absentee ballot. Provisional ballot.

**Comment by eventualbuddha** [comment]
@benadida to clarify, is this an enum with a few different values?

```ts
enum BallotType {
  Standard,
  Absentee,
  Provisional,
}
```

Or is this a bit field?

```ts
interface CompletedBallot {
  // …
  isStandard: boolean
  isAbsentee: boolean
  isProvisional: boolean
}
```

**Comment by benadida** [comment]
Enum. 

Separate bit for isTest (which we already have and doesn't change.)
